### ISSUE TITLE
Browser signature is different when the script is deployed on different hosts

### ISSUE THREAD

**Issue by jackiehamchen** [successtar/browser-signature#1]
Would it be possible to generate a unique browser signature regardless of hosts where the script it run?

E.g. Localhost: Signature_A
       Server A: Signature_A

Also, it would be great if there is an api to know the browser being used by the clients.

Thank you in advance.

**Comment by successtar** [comment]
Try the Usage with local storage option

https://github.com/successtar/browser-signature#usage-with-local-storage-implementation
