### ISSUE TITLE
Brave and Chromium giving same ID

### ISSUE THREAD

**Issue by SubhajitSarkar** [successtar/browser-signature#2]
I'm using Ubuntu 22

**Happening:**
When testing on Chromium and Brave browser, both are giving same Identifier

**Expecting:**
This should return a different unique ID instead of the same one.

Please let me know if you need any further information in this regard.

**Comment by successtar** [comment]
Try the Usage with local storage option

https://github.com/successtar/browser-signature#usage-with-local-storage-implementation
